# Generated by Django 2.0 on 2018-04-29 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='last_week',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='peak_position',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='weeks_on_chart',
            field=models.IntegerField(null=True),
        ),
    ]
