# Generated by Django 2.0 on 2018-04-29 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_auto_20180429_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='href',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AddField(
            model_name='artist',
            name='img',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AddField(
            model_name='artist',
            name='name',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
