# Generated by Django 2.0 on 2018-04-30 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0003_auto_20180429_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='href',
            field=models.CharField(default='none', max_length=200, null=True),
        ),
    ]
