# Generated by Django 2.0 on 2018-04-30 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0005_auto_20180429_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='peak_position',
            field=models.IntegerField(null=True),
        ),
    ]
